# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adam Dalal
email: adalal80@gmail.com
description: Senior PM building AI & data products. Writing about what I learn along the way.
url: "https://abdalal.com"
baseurl: ""
#twitter_username: adalal80
github_username:  adalal80

# Build settings
markdown: kramdown

header_pages:
  - index.html
  - about.md
  - portfolio.md
  - resume_ai.md
  - other.md
